apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trendz-app-pvc
  namespace: trendz
  labels:
    app: trendz-app-pvc-label
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---