apiVersion: v1
kind: ConfigMap
metadata:
  name: trendz-app-config
  namespace: trendz
  labels:
    name: trendz-app-config-label
data:
  trendz.conf: |
    # Mounted by trendz-app-config
    export LOG_FILENAME=trendz.out
    export LOADER_PATH=/usr/share/trendz/conf,/usr/share/trendz/extensions
    
    export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/trendz/data"
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/trendz/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/trendz/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">
    
        <appender name="fileLogAppender"
                  class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/trendz/trendz.log</file>
            <rollingPolicy
                    class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/trendz/trendz.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
                <maxFileSize>100MB</maxFileSize>
                <maxHistory>30</maxHistory>
                <totalSizeCap>3GB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
    
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
    
        <logger name="org.thingsboard.trendz" level="INFO" />
    
        <logger name="org.hibernate.engine.jdbc.spi.SqlExceptionHelper" level="WARN" />
        <logger name="org.springframework.security.web.FilterChainProxy" level="INFO" />
        <logger name="org.springframework.security.web.authentication.AnonymousAuthenticationFilter" level="INFO" />
        <logger name="org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor" level="INFO" />
    
        <!--    <logger name="org.thingsboard.trendz.service.provider.TbWebClient" level="TRACE" />-->
        <!--    <logger name="org.thingsboard.trendz.service.task.TaskRuntimeService" level="DEBUG" />-->
        <!--    <logger name="org.thingsboard.trendz.service.provider.TbRestDataSource" level="DEBUG" />-->
    
        <root level="INFO">
            <appender-ref ref="fileLogAppender"/>
            <appender-ref ref="STDOUT"/>
        </root>
    
    </configuration>
---