apiVersion: v1
kind: ConfigMap
metadata:
  name: trendz-python-executor-config
  namespace: trendz
  labels:
    name: trendz-python-executor-config-label
data:
  logback: |
    <?xml version="1.0" encoding="UTF-8" ?>
    
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">
    
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <Pattern>
                    %green(%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS}) | %highlight(%-5level) [%cyan(%-40thread)] %-60yellow(%C{1}): %msg %n%throwable
                </Pattern>
            </encoder>
        </appender>
    
    
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>
    
        <logger name="org.springframework.web.socket" level="INFO" />
        <logger name="org.thingsboard.trendz.pythonexecutor" level="DEBUG" />
        <logger name="org.thingsboard.trendz.pythonexecutor.service.engine.PythonScriptEngine" level="INFO" />
    
    </configuration>
---

