apiVersion: v1
kind: ConfigMap
metadata:
  name: trendz-python-executor-config
  namespace: trendz
  labels:
    name: trendz-python-executor-config-label
data:
  requirements.txt: |
    # Mounted by trendz-python-executor-config
    pandas==2.0.3
    numpy==1.24.3
    scikit-learn==1.3.0
    matplotlib==3.7.2
    seaborn==0.12.2
    requests==2.31.0
    pytz==2023.3
    plotly==5.15.0
    statsmodels==0.14.0
    scipy==1.11.1
    joblib==1.3.2

  python-executor.conf: |
    # Mounted by trendz-python-executor-config
    export LOG_FILENAME=python-executor.out
    export LOADER_PATH=/usr/share/python-executor/conf,/usr/share/python-executor/extensions
    
    export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/python-executor/data"
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/python-executor/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/python-executor/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <!-- Mounted by trendz-python-executor-config -->
    
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">
    
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
    
        <logger name="org.springframework.web.socket" level="INFO" />
        <logger name="org.thingsboard.trendz.pythonexecutor" level="INFO" />
        <logger name="org.thingsboard.trendz.pythonexecutor.service.engine.PythonScriptEngine" level="INFO" />
    
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>
    
    </configuration>

---

